exception: update CancelledStartRequest message
inform users to use 'terminate' vs 'stop' to destroy the cluster and
also to use 'listclusters' instead of listinstances to verify that the
cluster has been destroyed